In [3]:
# Practice most intensive PCA
import pandas as pd
import numpy as np
import math
from sklearn.model_selection import train_test_split

In [43]:
iris = pd.read_csv('datasets/iris.csv')
x = iris[[col for col in iris.columns if col != 'species']]
y = iris[['species']]
# center data
x -= x.mean(axis=0)
# x /= len(x)
# find cov matrix
cov_matrix = np.cov(x.T)
print("COV MATRIX")
print(cov_matrix)
eig_values, eig_vectors = np.linalg.eig(cov_matrix)
vector = eig_vectors[:, 0]
print('#CORR MATRIX')
corr_matrix = np.corrcoef(cov_matrix)
print(corr_matrix)
print('#'*10)

print(eig_values)
print(eig_vectors)
print('#'*10)
print(vector)
print(eig_vectors[0, 0])

total_var = 0
print(" VARIANCES ")
typo = x.values
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        v = typo[i, j]
        total_var += v ** 2

total_var /= len(x)
custom_var = 0
for i in range(len(x)):
    row = typo[i, :]
    custom_var += np.dot(row, vector)

vv = np.var(x)
#print(custom_var, total_var)
#print(custom_var / total_var)
print(vv)

COV MATRIX
[[ 0.68569351 -0.03926846  1.27368233  0.5169038 ]
 [-0.03926846  0.18800403 -0.32171275 -0.11798121]
 [ 1.27368233 -0.32171275  3.11317942  1.29638747]
 [ 0.5169038  -0.11798121  1.29638747  0.58241432]]
#CORR MATRIX
[[ 1.         -0.95957225  0.99057615  0.98463696]
 [-0.95957225  1.         -0.98626404 -0.99172367]
 [ 0.99057615 -0.98626404  1.          0.99919608]
 [ 0.98463696 -0.99172367  0.99919608  1.        ]]
##########
[4.22484077 0.24224357 0.07852391 0.02368303]
[[ 0.36158968 -0.65653988 -0.58099728  0.31725455]
 [-0.08226889 -0.72971237  0.59641809 -0.32409435]
 [ 0.85657211  0.1757674   0.07252408 -0.47971899]
 [ 0.35884393  0.07470647  0.54906091  0.75112056]]
##########
[ 0.36158968 -0.08226889  0.85657211  0.35884393]
0.3615896773814494
 VARIANCES 
sepal_length    0.681122
sepal_width     0.186751
petal_length    3.092425
petal_width     0.578532
dtype: float64
